version: '3.4'

services:
  emailsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "55001:80"

  loanrequestapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "55002:80"


  clientapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "55003:80"


  admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "55004:80"

